services:
  app:
    build: .
    ports:
      - '8080:8080'
    environment:
      TWITCH_APP_ID: ${TWITCH_APP_ID}
      TWITCH_APP_SECRET: ${TWITCH_APP_SECRET}
      TWITCH_APP_REDIRECT_URI: http://localhost:8080/redirect
      POSTGRES_DSN: postgres://postgres:postgres@postgres/postgres
    volumes:
      - .:/app:ro
    command:
      - uvicorn
      - '--host'
      - '0.0.0.0'
      - '--port'
      - '8080'
      - '--reload'
      - 'twitchemotes_server.server:APP'

    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:17
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "postgres"]
      interval: 5s
      timeout: 60s
      retries: 20

volumes:
  pgdata:
