name: Build image
run-name: ${{ forgejo.actor }} building image
on: [push]
jobs:
  Build:
    runs-on: docker
    container:
      image: node:22-alpine
    env:
      DOCKER_HOST: tcp://forgejo-dind:2375
    steps:
      - run: apk add --no-cache git openssh-client docker
      - uses: actions/checkout@v4
      - run: docker build -t registry.e4b4.eu/stream-emotes:latest .
      - run: docker push registry.e4b4.eu/stream-emotes:latest
